# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'keyboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for keyboard

end

target 'TuneSend' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TuneSend

  target 'TuneSendTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
