platform :ios, '11.2'
inhibit_all_warnings!

target 'keyboard' do
  use_frameworks!

  # Pods for keyboard

end

target 'tunesendReactNative' do
  use_frameworks!

  # Pods for tunesendReactNative

end

